/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Controller.ControllerAccount;
import Utilities.UserSessionManager;
import Controller.ControllerLogin;
import Entity.User;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

import javax.swing.JOptionPane;

/**
 *
 * @author sherr
 */
public class GuiAccount extends javax.swing.JFrame {

    ControllerLogin conLogin = new ControllerLogin();
    ControllerAccount conAccount = new ControllerAccount();

    /**
     * Creates new form GuiAccount
     */
    public GuiAccount() {
        initComponents();
        setLocationRelativeTo(null);

        txtImagePath.setVisible(false);
        getUserInfo();
    }

    public void getUserInfo() {

        // Get the current user's id_akun
        int userId = UserSessionManager.getCurrentUserId();

        // Set the username label text
        txtUsername.setText(conLogin.getUsernameById(userId));

        // Get the profile picture from conLogin
        byte[] imageData = conLogin.getPfpById(userId);

        if (imageData != null) {
            // Convert the byte array to an ImageIcon
            ImageIcon imageIcon = new ImageIcon(imageData);

            // Scale the image to fit lblImage
            Image scaledImage = imageIcon.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);

            // Create a new ImageIcon with the scaled image
            ImageIcon scaledImageIcon = new ImageIcon(scaledImage);

            // Set the ImageIcon to lblImage
            lblImage.setIcon(scaledImageIcon);
        } else {
            // Handle the case where there is no image
            System.out.println("No image");
            lblImage.setIcon(null); // Set lblImage to null or another default image
        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnChangeUsername = new javax.swing.JButton();
        btnDeleteAccount = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnUpdatePfp = new javax.swing.JButton();
        txtImagePath = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        btnChangePfp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 59, 106));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnChangeUsername.setBackground(new java.awt.Color(126, 123, 158));
        btnChangeUsername.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        btnChangeUsername.setForeground(new java.awt.Color(0, 0, 0));
        btnChangeUsername.setIcon(new javax.swing.ImageIcon("D:\\Semester 3\\Projek UAS OOP\\icons library\\Icon Pack User Interface (Flat Gradient)\\change username 64px (UICONS).png")); // NOI18N
        btnChangeUsername.setText("       Change Username");
        btnChangeUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnChangeUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(btnChangeUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 220, 200));

        btnDeleteAccount.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteAccount.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        btnDeleteAccount.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteAccount.setIcon(new javax.swing.ImageIcon("D:\\Semester 3\\Projek UAS OOP\\icons library\\Icon Pack User Interface (Flat Gradient)\\skull 32px (Basic Miscellany Lineal color).png")); // NOI18N
        btnDeleteAccount.setText("Delete Account");
        btnDeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 670, 160, -1));

        btnChangePassword.setBackground(new java.awt.Color(126, 123, 158));
        btnChangePassword.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        btnChangePassword.setForeground(new java.awt.Color(0, 0, 0));
        btnChangePassword.setIcon(new javax.swing.ImageIcon("D:\\Semester 3\\Projek UAS OOP\\icons library\\Icon Pack User Interface (Flat Gradient)\\change password 64px ( Gregor Color Solid).png")); // NOI18N
        btnChangePassword.setText("                    Change Password");
        btnChangePassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        jPanel1.add(btnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 280, 100));

        btnUpdatePfp.setBackground(new java.awt.Color(126, 123, 158));
        btnUpdatePfp.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdatePfp.setIcon(new javax.swing.ImageIcon("D:\\Semester 3\\Projek UAS OOP\\icons library\\Icon Pack User Interface (Flat Gradient)\\Change Pfp 64px (Wahyu Adam Basic Outline).png")); // NOI18N
        btnUpdatePfp.setText("           Change Profile Picture");
        btnUpdatePfp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUpdatePfp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePfpActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdatePfp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 280, 90));
        jPanel1.add(txtImagePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 160, -1));

        lblImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 162, 151));

        btnChangePfp.setForeground(new java.awt.Color(0, 0, 0));
        btnChangePfp.setIcon(new javax.swing.ImageIcon("D:\\Semester 3\\Projek UAS OOP\\icons library\\Icon Pack User Interface (Flat Gradient)\\image ( Graphic style).png")); // NOI18N
        btnChangePfp.setText("Upload");
        btnChangePfp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePfpActionPerformed(evt);
            }
        });
        jPanel1.add(btnChangePfp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Semester 3\\Projek UAS OOP\\ace-achiever-high-resolution-logo - Copy - Copy (2).png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 120, 60));

        jLabel1.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("My Account");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        lblBack.setIcon(new javax.swing.ImageIcon("D:\\Semester 3\\Projek UAS OOP\\icons library\\Icon Pack User Interface (Flat Gradient)\\back icon (bharat icons basic).png")); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanel1.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(250, 236, 226));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 470, 10));

        jSeparator2.setForeground(new java.awt.Color(250, 236, 226));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 520, 10));

        jLabel2.setFont(new java.awt.Font("Lato", 3, 36)); // NOI18N
        jLabel2.setText("EDIT YOUR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 210, -1));

        jLabel4.setFont(new java.awt.Font("Lato", 3, 36)); // NOI18N
        jLabel4.setText("PROFILE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 160, -1));

        jLabel5.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel5.setText("Username");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        txtUsername.setBackground(new java.awt.Color(126, 123, 158));
        txtUsername.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        txtUsername.setText("<<Username>>");
        txtUsername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeUsernameActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to change your username?\nThis action cannot be undone.",
                "Confirmation",
                JOptionPane.YES_NO_OPTION
        );

        // Check the user's choice
        if (choice == JOptionPane.YES_OPTION) {
            // User clicked 'Yes,' proceed with the username change
            String newUsername = txtUsername.getText();// retrieve the new username (e.g., from a text field)
            // Update the username in the database
            updateUsernameInDatabase(newUsername);

            // Update the displayed username
            txtUsername.setText(newUsername);

            // Optionally, provide feedback to the user that the change was successful
            JOptionPane.showMessageDialog(
                    null,
                    "Username changed successfully.",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }

    }//GEN-LAST:event_btnChangeUsernameActionPerformed

    private void updateUsernameInDatabase(String newUsername) {
        int userId = UserSessionManager.getCurrentUserId();
        User updatedUser = new User();
        updatedUser.setId_user(userId);
        updatedUser.setUsername(newUsername);

        ControllerAccount controllerAccount = new ControllerAccount();
        boolean success = controllerAccount.updateUsername(updatedUser);

        if (success) {
            JOptionPane.showMessageDialog(null, "Username has been successfully updated");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to update Username", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnDeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccountActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to delete your account?\nThis action cannot be undone.",
                "Confirmation",
                JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {
            // User clicked 'Yes,' proceed with account deletion
            // Get the current user ID
            int userId = UserSessionManager.getCurrentUserId();

            // Perform the account deletion
            boolean deletionSuccess = conAccount.deleteAccount(userId);

            // Check if the deletion was successful
            if (deletionSuccess) {
                // Optionally, provide feedback to the user that the account was deleted
                JOptionPane.showMessageDialog(
                        null,
                        "Account deleted successfully.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                );
                GuiLogin guiLogin = new GuiLogin();
                guiLogin.setVisible(true);
                dispose();

                // TODO: Add code to handle any additional steps after account deletion, such as logging out or navigating to a different screen.
            } else {
                // Provide an error message if the deletion fails
                JOptionPane.showMessageDialog(
                        null,
                        "Failed to delete the account. Please try again.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnDeleteAccountActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed

        GuiChangePassword guiChangePassword = new GuiChangePassword();
        guiChangePassword.setVisible(true);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here:
        GuiSettings guiSettings = new GuiSettings();
        guiSettings.setVisible(true);

        dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void btnChangePfpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePfpActionPerformed
        // TODO add your handling code here:

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(null);
        File file = fileChooser.getSelectedFile();

        if (file != null) {
            namaFilePhoto = file.getAbsolutePath();
            txtImagePath.setText(namaFilePhoto);

            try {
                // Read image file and convert it to byte array
                BufferedImage originalImage = ImageIO.read(file);
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                ImageIO.write(originalImage, "jpeg", bos);
                pfpImage = bos.toByteArray();

                // Display the selected image
                ImageIcon scaledImageIcon = new ImageIcon(originalImage.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH));
                lblImage.setIcon(scaledImageIcon);

            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error reading the image file.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_btnChangePfpActionPerformed

    private void btnUpdatePfpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePfpActionPerformed
        // TODO add your handling code here:
        // Create User object and update profile picture
        Boolean hasil;

        User user = new User();
        user.setProfile_picture(pfpImage);

        // Get the current user ID
        int userId = UserSessionManager.getCurrentUserId();
        user.setId_user(userId);

        // Update the profile picture in the database
        hasil = conAccount.updateProfilePicture(user);

        if (hasil) {
            // Optionally, update the displayed profile picture in the UI
            ImageIcon scaledImageIcon = new ImageIcon(user.getProfile_picture());
            lblImage.setIcon(scaledImageIcon);

            JOptionPane.showMessageDialog(null, "Profile Picture successfully updated");
            
        } else {
            JOptionPane.showMessageDialog(null, "Profile Picture failed to be updated", "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdatePfpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiAccount.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiAccount.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiAccount.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiAccount.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnChangePfp;
    private javax.swing.JButton btnChangeUsername;
    private javax.swing.JButton btnDeleteAccount;
    private javax.swing.JButton btnUpdatePfp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTextField txtImagePath;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
    String namaFilePhoto = null;
    private ImageIcon pfpIcon = null;
    byte[] pfpImage = null;
}
