/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Controller.ControllerReminder;
import Utilities.UserSessionManager;
import Entity.Reminder;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author sherr
 */
public class GuiReminder extends javax.swing.JFrame {

    ControllerReminder conReminder = new ControllerReminder();
    private DefaultTableModel model;

    /**
     * Creates new form GuiReminder
     */
    public GuiReminder() {
        initComponents();
        setLocationRelativeTo(null);

        // Initialize the table model
        model = (DefaultTableModel) tabelReminder.getModel();

        // Set auto-resize mode after setting preferred widths
        tabelReminder.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabelReminder.setRowHeight(40);

        getData();
        refreshTable();

        // Add FocusListener to clear the text field when it gains focus
        txtTitle.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                String currentText = txtTitle.getText();
                if (currentText.equals("Add a title") || currentText.isEmpty()) {
                    txtTitle.setText(null);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                String currentText = txtTitle.getText();
                if (currentText.isEmpty()) {
                    txtTitle.setText("Add a title");
                }
            }
        });

        // Add FocusListener to clear the text field when it gains focus
        txtNote.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                String currentText = txtNote.getText();
                if (currentText.equals("Add a note") || currentText.isEmpty()) {
                    txtNote.setText(null);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                String currentText = txtNote.getText();
                if (currentText.isEmpty()) {
                    txtNote.setText("Add a note");
                }
            }
        });

    }

    private void getData() {
        DefaultTableModel dtm = (DefaultTableModel) tabelReminder.getModel();
        dtm.setRowCount(0);

        // Get the current user's id_akun
        int userId = UserSessionManager.getCurrentUserId();

        List<Reminder> listReminder = conReminder.getRemindersForUser(userId);
        String[] data = new String[4];
        for (Reminder newReminder : listReminder) {
            data[0] = Integer.toString(newReminder.getId_reminder());
            data[1] = newReminder.getTitle();
            data[2] = newReminder.getDate();
            data[3] = newReminder.getNote();
            dtm.addRow(data);
        }
    }

    private void clearData() {
        txtTitle.setText("");
        dcDate.setCalendar(null);
        txtNote.setText("");
    }

    // Refresh the table with the latest data
    private void refreshTable() {
        // Clear the existing data in the table
        model.setRowCount(0);

        // Get the current user's id_akun
        int userId = UserSessionManager.getCurrentUserId();

        // Retrieve all reminders for the specific user
        List<Reminder> listReminder = conReminder.getRemindersForUser(userId);

        // Add the reminders to the table model
        for (Reminder reminder : listReminder) {
            Object[] rowData = {reminder.getId_reminder(), reminder.getTitle(), reminder.getDate(), reminder.getNote()};
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        txtNote = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        dcDate = new com.toedter.calendar.JDateChooser();
        txtId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelReminder = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblUpdate = new javax.swing.JLabel();
        lblDelete = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        lblClear = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(126, 123, 158));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reminder");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        txtTitle.setBackground(new java.awt.Color(126, 123, 158));
        txtTitle.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        txtTitle.setText("Add a title");
        txtTitle.setBorder(null);
        txtTitle.setOpaque(true);
        jPanel1.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 280, 30));

        txtNote.setBackground(new java.awt.Color(126, 123, 158));
        txtNote.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        txtNote.setText("Add a note");
        txtNote.setBorder(null);
        txtNote.setOpaque(true);
        jPanel1.add(txtNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 310, 30));

        jLabel2.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Semester 3\\Projek UAS OOP\\icons library\\Icon Pack User Interface (Flat Gradient)\\Reminder 24 px( Bell free icon).png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Semester 3\\Projek UAS OOP\\icons library\\Icon Pack User Interface (Flat Gradient)\\date 24px ( super basic ).png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 825, -1, -1));

        btnSave.setBackground(new java.awt.Color(56, 63, 104));
        btnSave.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 0, 0));
        btnSave.setText("Save");
        btnSave.setOpaque(true);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 85, 30));

        dcDate.setBackground(new java.awt.Color(126, 123, 158));
        dcDate.setForeground(new java.awt.Color(126, 123, 158));
        dcDate.setToolTipText("");
        dcDate.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jPanel1.add(dcDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 131, 30));

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(126, 123, 158));
        txtId.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        txtId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 50, -1));

        jLabel6.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel6.setText("ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        tabelReminder.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        tabelReminder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Date", "Note"
            }
        ));
        tabelReminder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelReminderMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelReminder);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 388, 688, 360));

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Semester 3\\Projek UAS OOP\\icons library\\Icon Pack User Interface (Flat Gradient)\\back icon (bharat icons basic).png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Semester 3\\Projek UAS OOP\\icons library\\Icon Pack User Interface (Flat Gradient)\\note 24px ( uicons).png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(250, 236, 226));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 310, 20));

        jSeparator2.setForeground(new java.awt.Color(250, 236, 226));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 312, 10));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Semester 3\\Projek UAS OOP\\icons library\\Stickers\\Reminder 256px (Tomomi The Cat Lineal Color).png")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 242, -1));

        jSeparator3.setForeground(new java.awt.Color(250, 236, 226));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 400, 20));

        lblUpdate.setIcon(new javax.swing.ImageIcon("D:\\Semester 3\\Projek UAS OOP\\icons library\\Icon Pack User Interface (Flat Gradient)\\pencil 24px(special flat).png")); // NOI18N
        lblUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUpdateMouseClicked(evt);
            }
        });
        jPanel1.add(lblUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, -1, -1));

        lblDelete.setIcon(new javax.swing.ImageIcon("D:\\Semester 3\\Projek UAS OOP\\icons library\\Icon Pack User Interface (Flat Gradient)\\trash 24px( bqlqn lineal).png")); // NOI18N
        lblDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDeleteMouseClicked(evt);
            }
        });
        jPanel1.add(lblDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(250, 236, 226));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 310, 15));

        jSeparator5.setForeground(new java.awt.Color(250, 236, 226));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 400, 15));

        lblClear.setBackground(new java.awt.Color(126, 123, 158));
        lblClear.setForeground(new java.awt.Color(0, 0, 0));
        lblClear.setIcon(new javax.swing.ImageIcon("D:\\Semester 3\\Projek UAS OOP\\icons library\\Icon Pack User Interface (Flat Gradient)\\Clear 24px.png")); // NOI18N
        lblClear.setText("Clear Field");
        lblClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClearMouseClicked(evt);
            }
        });
        jPanel1.add(lblClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // Disable the button to prevent multiple clicks
        btnSave.setEnabled(false);

        // Collect data from text fields
        String title = txtTitle.getText();
        Date tanggal = dcDate.getDate();
        String note = txtNote.getText();

        // Validate that all required fields are filled
        if (title.isEmpty() || tanggal == null) {
            JOptionPane.showMessageDialog(this, "Title and Date are required fields.", "Error", JOptionPane.ERROR_MESSAGE);
            btnSave.setEnabled(true);
            return;
        }

        // Convert Date to String using SimpleDateFormat
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(tanggal);

        // Get the current user's id_akun
        int id_akun = UserSessionManager.getCurrentUserId();

        // Create a new Reminder object
        Reminder newReminder = new Reminder();
        newReminder.setId_akun(id_akun);
        newReminder.setTitle(title);
        newReminder.setDate(date);
        newReminder.setNote(note);

        // Create an instance of ControllerReminder
        ControllerReminder controllerReminder = new ControllerReminder();

        // Call the addReminder method
        boolean success = controllerReminder.addReminder(newReminder);

        // Handle success or failure
        if (success) {
            JOptionPane.showMessageDialog(this, "Reminder added successfully!");
            // You can add further actions or messages here

            // Refresh the table with the latest data
            refreshTable();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add reminder.", "Error", JOptionPane.ERROR_MESSAGE);
            // Handle failure, show an error message, etc.
        }

        // Enable the button after the operation is complete
        btnSave.setEnabled(true);

        clearData();
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tabelReminderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelReminderMouseClicked
        // TODO add your handling code here:
        int row = tabelReminder.getSelectedRow();

        TableModel model = tabelReminder.getModel();
        txtId.setText(model.getValueAt(row, 0).toString());
        txtTitle.setText(model.getValueAt(row, 1).toString());

        // Retrieve the date as a String from the table model
        String dateString = model.getValueAt(row, 2).toString();

        try {
            // Parse the String to a java.util.Date
            java.util.Date utilDate = new SimpleDateFormat("yyyy-MM-dd").parse(dateString);

            // Set the date in the JDateChooser
            dcDate.setDate(utilDate);
        } catch (ParseException ex) {
            ex.printStackTrace(); // Handle the exception appropriately
        }

        txtNote.setText(model.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tabelReminderMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        GuiAgenda guiAgenda = new GuiAgenda();
        guiAgenda.setVisible(true);

        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void lblUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUpdateMouseClicked
        // TODO add your handling code here:
        int row = tabelReminder.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(lblUpdate, "Choose at least 1 data", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idUpdate = Integer.parseInt(tabelReminder.getModel().getValueAt(row, 0).toString());
        String newTitle = txtTitle.getText();
        Date newDate = dcDate.getDate();
        String newDateStr = null;

        if (newDate != null) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            newDateStr = dateFormat.format(newDate);
        }

        String newNote = txtNote.getText();

        Reminder newReminder = new Reminder();
        newReminder.setId_reminder(idUpdate);
        newReminder.setTitle(newTitle);
        newReminder.setDate(newDateStr);
        newReminder.setNote(newNote);

        // Update the reminder using the newReminder object
        boolean updateSuccess = conReminder.updateReminder(newReminder);

        if (updateSuccess) {
            JOptionPane.showMessageDialog(null, "Data has been successfully updated");
            getData();
            refreshTable();
        } else {
            JOptionPane.showMessageDialog(null, "Failed to update data", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lblUpdateMouseClicked

    private void lblDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteMouseClicked

        // TODO add your handling code here:
        int row = tabelReminder.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(lblUpdate, "Choose at least 1 data", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idDelete = Integer.parseInt(tabelReminder.getModel().getValueAt(row, 0).toString());
        conReminder.deleteReminder(idDelete);

        JOptionPane.showMessageDialog(null, "Data has been Deleted");

        getData();
        refreshTable();
    }//GEN-LAST:event_lblDeleteMouseClicked

    private void lblClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearMouseClicked
        // TODO add your handling code here:
        clearData();
    }//GEN-LAST:event_lblClearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiReminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiReminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiReminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiReminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiReminder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser dcDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblClear;
    private javax.swing.JLabel lblDelete;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JTable tabelReminder;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
